//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarOwner = new HashSet<CarOwner>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int PlaceRegId { get; set; }
        public int CountryId { get; set; }
        public decimal NumberBody { get; set; }
        public decimal NumberEngine { get; set; }
        public decimal NumberChassis { get; set; }
    
        public virtual ICollection<CarOwner> CarOwner { get; set; }
        public virtual Country Countries { get; set; }
        public virtual Country Countries1 { get; set; }
        public virtual Model Models { get; set; }
    }
}
