//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int Id { get; set; }
        public int ProduserId { get; set; }
        public int BodyTypesId { get; set; }
        public string Name { get; set; }
    
        public virtual BodyType BodyTypes { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Produser Produsers { get; set; }
    }
}
