//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerFine
    {
        public int Id { get; set; }
        public int FineTypeId { get; set; }
        public int OwnerId { get; set; }
    
        public virtual FinesType FinesTypes { get; set; }
        public virtual Owner Owners { get; set; }
    }
}
