//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.CarOwner = new HashSet<CarOwner>();
            this.OwnerFines = new HashSet<OwnerFine>();
            this.Rights = new HashSet<Right>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<CarOwner> CarOwner { get; set; }
        public virtual ICollection<OwnerFine> OwnerFines { get; set; }
        public virtual ICollection<Right> Rights { get; set; }
    }
}
