//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int RightTypeId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual RightsType RightsTypes { get; set; }
        public virtual Owner Owners { get; set; }
    }
}
